"""create user model

Revision ID: 3b72015db923
Revises: 8abff47f0785
Create Date: 2024-06-25 20:58:45.551027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b72015db923'
down_revision: Union[str, None] = '8abff47f0785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('photo_public_id', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('transform_url', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_column('posts', 'photo')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', 'moderator', name='role'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', 'moderator', name='role'),
               nullable=False)
    op.add_column('posts', sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('posts', 'rating')
    op.drop_column('posts', 'transform_url')
    op.drop_column('posts', 'photo_public_id')
    op.drop_column('posts', 'photo_url')
    # ### end Alembic commands ###
